/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classes.InscritosEvento;
import classes.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import meuPacote.ValidaCPF;

/**
 *
 * @author P2
 */
public class AddAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form AddAminsitrador
     */
    public AddAdministrador() {
        initComponents();

        /*txtCpf.setEnabled(false);
        btnNovo.setEnabled(true);
        btnSalvar.setEnabled(false);
        txtCpfRetirar.setEnabled(false);
        btnNovoRetirar.setEnabled(true);
        btnSalvarRetirar.setEnabled(false);*/

        ///
        DefaultTableModel dtm = (DefaultTableModel) tabelaPermissao.getModel();
        for (int i = 0; i < Usuario.usuarios.size(); i++) {
            if (Usuario.usuarios.get(i).isPermissao() == true) {
                dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                    "Administrador"});
            } else {
                dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                    "Usuário Comum"});
            }

        }
        btnAdd.setEnabled(false);
        btnRemove.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPermissao = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCpfBuscar = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mudar Permissão"));

        tabelaPermissao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Permissão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPermissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaPermissaoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPermissao);

        btnAdd.setText("Adicionar Permissão");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remover Permissão");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF:");

        try {
            txtCpfBuscar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Selecione o usuário para adicionar ou remover a permissão de administrador");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(39, 39, 39)
                                .addComponent(btnRemove))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(txtCpfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnBuscar))))
                    .addComponent(jSeparator1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCpfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int linhaSel = tabelaPermissao.getSelectedRow();
        String cpf = tabelaPermissao.getValueAt(linhaSel, 1).toString();
        int pos = -1;
        for (int i = 0; i < Usuario.usuarios.size(); i++) {
            if (cpf.equals(Usuario.usuarios.get(i).getCpf())) {
                pos = i;

            }
        }
        if (pos == -1) {
            JOptionPane.showMessageDialog(null, "CPF NÃO ENCONTRADO");
        } else {

            Usuario.usuarios.get(pos).setPermissao(true);
            JOptionPane.showMessageDialog(null, "FUNÇÃO DE ADMINISTRADOR ATRIBUIDA COM SUCESSO");
            tabelaPermissao.setValueAt("Administrador", linhaSel, 2);
            btnAdd.setEnabled(false);
            btnRemove.setEnabled(false);

            //
            DefaultTableModel tblRemove = (DefaultTableModel) tabelaPermissao.getModel();
            tblRemove.setNumRows(0);

            DefaultTableModel dtm = (DefaultTableModel) tabelaPermissao.getModel();
            for (int i = 0; i < Usuario.usuarios.size(); i++) {
                if (Usuario.usuarios.get(i).isPermissao() == true) {
                    dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                        "Administrador"});
                } else {
                    dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                        "Usuário Comum"});
                }

            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tabelaPermissaoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPermissaoMouseReleased
        // TODO add your handling code here:
        if (tabelaPermissao.getSelectedRow() != -1) {
            int linhaSel = tabelaPermissao.getSelectedRow();
            String cpf = tabelaPermissao.getValueAt(linhaSel, 1).toString();
            int pos = -1;
            for (int i = 0; i < Usuario.usuarios.size(); i++) {
                if (cpf.equals(Usuario.usuarios.get(i).getCpf())) {
                    pos = i;
                }
            }
            if (pos == -1) {
                JOptionPane.showMessageDialog(null, "CPF NÃO ENCONTRADO");
            } else {
                if (Usuario.usuarios.get(pos).isPermissao() == true) {
                    btnRemove.setEnabled(true);
                    btnAdd.setEnabled(false);
                } else {
                    btnAdd.setEnabled(true);
                    btnRemove.setEnabled(false);

                }
            }

        }
    }//GEN-LAST:event_tabelaPermissaoMouseReleased

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int linhaSel = tabelaPermissao.getSelectedRow();
        String cpf = tabelaPermissao.getValueAt(linhaSel, 1).toString();
        int pos = -1, cont = 0;
        for (int i = 0; i < Usuario.usuarios.size(); i++) {
            if (cpf.equals(Usuario.usuarios.get(i).getCpf())) {
                pos = i;
            }
            if (Usuario.usuarios.get(i).isPermissao() == true) {
                cont++;
            }
        }
        if (pos == -1) {
            JOptionPane.showMessageDialog(null, "CPF NÃO ENCONTRADO");
        } else {
            if (cont == 1) {
                JOptionPane.showMessageDialog(null, "SISTEMA NÃO PODE FICAR SEM ADMINISTRADOR");
            } else {
                Usuario.usuarios.get(pos).setPermissao(false);
                JOptionPane.showMessageDialog(null, "FUNÇÃO DE ADMINISTRADOR RETIRADA COM SUCESSO");
                tabelaPermissao.setValueAt("Usuário Comum", linhaSel, 2);
                btnRemove.setEnabled(false);
                btnAdd.setEnabled(false);

                //
                DefaultTableModel tblRemove = (DefaultTableModel) tabelaPermissao.getModel();
                tblRemove.setNumRows(0);

                DefaultTableModel dtm = (DefaultTableModel) tabelaPermissao.getModel();
                for (int i = 0; i < Usuario.usuarios.size(); i++) {
                    if (Usuario.usuarios.get(i).isPermissao() == true) {
                        dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                            "Administrador"});
                    } else {
                        dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                            "Usuário Comum"});
                    }

                }
            }

        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int linhaSel = tabelaPermissao.getSelectedRow();
        String cpf = txtCpfBuscar.getText();
        int pos = -1;
        for (int i = 0; i < Usuario.usuarios.size(); i++) {
            if (cpf.equals(Usuario.usuarios.get(i).getCpf())) {
                pos = i;
            }
        }
        if (cpf.equals("")) {
            DefaultTableModel tblRemove = (DefaultTableModel) tabelaPermissao.getModel();
            tblRemove.setNumRows(0);

            DefaultTableModel dtm = (DefaultTableModel) tabelaPermissao.getModel();
            for (int i = 0; i < Usuario.usuarios.size(); i++) {
                if (Usuario.usuarios.get(i).isPermissao() == true) {
                    dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                        "Administrador"});
                } else {
                    dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                        "Usuário Comum"});
                }

            }
        } else if (pos == -1) {
            JOptionPane.showMessageDialog(null, "USUÁRIO NÃO ENCONTRADO NO EVENTO");
            DefaultTableModel tblRemove = (DefaultTableModel) tabelaPermissao.getModel();
            tblRemove.setNumRows(0);

            DefaultTableModel dtm = (DefaultTableModel) tabelaPermissao.getModel();
            for (int i = 0; i < Usuario.usuarios.size(); i++) {
                if (Usuario.usuarios.get(i).isPermissao() == true) {
                    dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                        "Administrador"});
                } else {
                    dtm.addRow(new Object[]{Usuario.usuarios.get(i).getNome(), Usuario.usuarios.get(i).getCpf(),
                        "Usuário Comum"});
                }
            }
        } else {
            DefaultTableModel tblRemove = (DefaultTableModel) tabelaPermissao.getModel();
            tblRemove.setNumRows(0);
            DefaultTableModel dtm = (DefaultTableModel) tabelaPermissao.getModel();
            String permissao;
            if (Usuario.usuarios.get(pos).isPermissao() == true) {
                permissao = "Administrador";
            } else {
                permissao = "Usuário Comum";
            }
            dtm.addRow(new Object[]{Usuario.usuarios.get(pos).getNome(), Usuario.usuarios.get(pos).getCpf(),
                permissao});
            
            txtCpfBuscar.setText("");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaPermissao;
    private javax.swing.JFormattedTextField txtCpfBuscar;
    // End of variables declaration//GEN-END:variables
}
