/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import classes.InscritosEvento;
import classes.Usuario;
import javax.swing.JOptionPane;
import interfaces.Executavel;
import static java.lang.System.exit;

/**
 *
 * @author P2
 */
public class EditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form EditarPerfil
     */
    public EditarPerfil() {
        initComponents();
        btnSalvar.setEnabled(false);
        txtNome.setEnabled(false);
        txtSenhaNova.setEnabled(false);
        txtSenhaNovamente.setEnabled(false);
        btnSalvarNome.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSenhaNova = new javax.swing.JPasswordField();
        txtSenhaNovamente = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalvarNome = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Dados"));

        jLabel1.setText("CPF:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Senha:");

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome:");

        jLabel4.setText("Senha Nova:");

        jLabel5.setText("Informe Novamente:");

        btnSalvar.setText("Salvar senha");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSalvarNome.setText("Salvar nome");
        btnSalvarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(txtSenhaNova, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSenhaNovamente, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSenha)
                            .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvarNome)
                            .addComponent(btnSalvar))))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSenhaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnSalvar)
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(30, 30, 30)
                .addComponent(btnSalvarNome)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        String CPF = txtCpf.getText();
        String senha = String.valueOf(txtSenha.getPassword());
        int pos = -1;
        if (CPF.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "HÁ CAMPO EM BRANCO");
        } else {
            for (int i = 0; i < Usuario.usuarios.size(); i++) {
                if (CPF.equals(Usuario.usuarios.get(i).getCpf())) {
                    pos = i;
                }
            }
            if (pos == -1) {
                JOptionPane.showMessageDialog(null, "CPF NÃO ENCONTRADO");
            } else {

                if (senha.equals(Usuario.usuarios.get(pos).getSenha()) == false) {
                    JOptionPane.showMessageDialog(null, "DADOS INCORRETOS");
                } else {
                    btnSalvar.setEnabled(true);
                    txtNome.setEnabled(true);
                    txtSenhaNova.setEnabled(true);
                    txtSenhaNovamente.setEnabled(true);
                    txtNome.setText(Usuario.usuarios.get(pos).getNome());
                    btnSalvarNome.setEnabled(true);
                }
            }
        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        String cpf = txtCpf.getText();
        String senha = String.valueOf(txtSenha.getPassword());
        int pos = -1;
        if (cpf.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "EXISTE CAMPO EM BRANCO");
        } else {
            for (int i = 0; i < Usuario.usuarios.size(); i++) {
                if (cpf.equals(Usuario.usuarios.get(i).getCpf())) {
                    pos = i;
                }
            }
            if (pos == -1) {
                JOptionPane.showMessageDialog(null, "CPF NÃO ENCONTRADO");
            } else {

                if (senha.equals(Usuario.usuarios.get(pos).getSenha())) {
                    int cont = 0, poss = 0;
                    for (int i = 0; i < Usuario.usuarios.size(); i++) {
                        if (Usuario.usuarios.get(i).isPermissao() == true) {
                            cont++;
                            poss = i;
                        }
                    }
                    if (cont == 1 && Usuario.usuarios.get(poss).getCpf().equals(cpf)) {
                        JOptionPane.showMessageDialog(null, "O SISTEMA NÃO PODE FICAR SEM ADMINISTRADOR");
                    } else {
                        int excluir = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir sua conta?", "Alerta", JOptionPane.YES_NO_OPTION);

                        if (excluir == JOptionPane.YES_OPTION) {
                            this.dispose();

                            int pos2 = -1, j = 0, i = 0;

                            for (i = (InscritosEvento.inscritos.size() - 1); i >= 0; i--) {
                                if (cpf.equals(InscritosEvento.inscritos.get(i).getCpf())) {
                                    InscritosEvento.inscritos.remove(i);
                                }

                            }

                            Usuario.usuarios.remove(pos);
                            txtCpf.setEnabled(false);
                            txtSenha.setEnabled(false);
                            txtSenhaNova.setEnabled(false);
                            txtSenhaNovamente.setEnabled(false);
                            btnSalvar.setEnabled(false);
                            btnAlterar.setEnabled(false);
                            txtNome.setEnabled(false);
                            txtNome.setText("");
                            txtSenhaNova.setText("");
                            txtSenhaNovamente.setText("");
                            txtCpf.setText("");
                            txtSenha.setText("");
                            btnExcluir.setEnabled(false);

                            JOptionPane.showMessageDialog(null, "CONTA EXCLUÍDA COM SUCESSO");
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "DADOS INCORRETOS");
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        String CPF = txtCpf.getText();
        int pos = -1;
        for (int i = 0; i < Usuario.usuarios.size(); i++) {
            if (CPF.equals(Usuario.usuarios.get(i).getCpf())) {
                pos = i;
            }
        }
        String senhaNova = String.valueOf(txtSenhaNova.getPassword());
        String senhaNovamente = String.valueOf(txtSenhaNovamente.getPassword());
        if (senhaNova.equals("") || senhaNovamente.equals("")) {
            JOptionPane.showMessageDialog(null, "HÁ CAMPO EM BRANCO");
        } else if (senhaNova.equals(Usuario.usuarios.get(pos).getSenha())) {
            JOptionPane.showMessageDialog(null, "SENHA NOVA IGUAL A ANTIGA");
        } else {
            if (senhaNova.equals(senhaNovamente)) {
                //String nome = txtNome.getText();
                //Usuario.usuarios.get(pos).setNome(nome);
                Usuario.usuarios.get(pos).setSenha(senhaNova);
                JOptionPane.showMessageDialog(null, "SENHA MUDADA COM SUCESSO");
                txtSenhaNova.setEnabled(false);
                txtSenhaNovamente.setEnabled(false);
                btnSalvar.setEnabled(false);
                //txtNome.setEnabled(false);
                //txtNome.setText("");
                txtSenhaNova.setText("");
                txtSenhaNovamente.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "SENHAS DIFERENTES");
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarNomeActionPerformed
        // TODO add your handling code here:
        String CPF = txtCpf.getText();
        String senha = String.valueOf(txtSenha.getPassword());
        int pos = -1;
        for (int i = 0; i < Usuario.usuarios.size(); i++) {
            if (CPF.equals(Usuario.usuarios.get(i).getCpf())) {
                pos = i;
            }
        }
        if (CPF.equals("") || senha.equals("")) {
            JOptionPane.showMessageDialog(null, "HÁ CAMPO EM BRANCO");
        } else if (senha.equals(Usuario.usuarios.get(pos).getSenha())) {
            String nome = txtNome.getText();
            Usuario.usuarios.get(pos).setNome(nome);
            txtNome.setEnabled(false);
            txtNome.setText("");
            btnSalvarNome.setEnabled(false);
            JOptionPane.showMessageDialog(null, "NOME MUDADO COM SUCESSO");
        } else {
            JOptionPane.showMessageDialog(null, "DADOS INCORRETOS");
        }
    }//GEN-LAST:event_btnSalvarNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvarNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaNova;
    private javax.swing.JPasswordField txtSenhaNovamente;
    // End of variables declaration//GEN-END:variables
}
